/**
 * DOM 引用集中（阶段 1）
 */
(function initDom(TD) {
  TD.dom = {
    ticketCountEl: document.getElementById("ticketCount"),
    nextTickEl: document.getElementById("nextTick"),
    handlerInput: document.getElementById("handlerInput"),
    intervalInput: document.getElementById("intervalInput"),
    autoGroupInput: document.getElementById("autoGroupInput"),
    autoSendMessageInput: document.getElementById("autoSendMessageInput"),
    titlePatrolLogInput: document.getElementById("titlePatrolLogInput"),
    titleOnNewAutoInput: document.getElementById("titleOnNewAutoInput"),
    startBtn: document.getElementById("startBtn"),
    logList: document.getElementById("logList"),
    ttWebview: document.getElementById("ttWebview"),
    webviewLoadingHint: document.getElementById("webviewLoadingHint"),
    templatesSaveBtn: document.getElementById("templatesSaveBtn"),
    templatesAddRuleBtn: document.getElementById("templatesAddRuleBtn"),
    templatesPreviewBtn: document.getElementById("templatesPreviewBtn"),
    defaultMessageTextarea: document.getElementById("defaultMessageTextarea"),
    defaultMessageEnTextarea: document.getElementById("defaultMessageEnTextarea"),
    templatesRulesList: document.getElementById("templatesRulesList"),
    tabLogsBtn: document.getElementById("tabLogsBtn"),
    tabTicketsBtn: document.getElementById("tabTicketsBtn"),
    tabTemplatesBtn: document.getElementById("tabTemplatesBtn"),
    openLogsDirBtn: document.getElementById("openLogsDirBtn"),
    panelLogs: document.getElementById("panelLogs"),
    panelTickets: document.getElementById("panelTickets"),
    panelTemplates: document.getElementById("panelTemplates"),
    prioritySortBtn: document.getElementById("prioritySortBtn"),
    createdSortBtn: document.getElementById("createdSortBtn"),
    ticketTitleSearchInput: document.getElementById("ticketTitleSearchInput"),
    ticketCategorySelect: document.getElementById("ticketCategorySelect"),
    ticketOnlyMineInput: document.getElementById("ticketOnlyMineInput"),
    ticketHideClosedInput: document.getElementById("ticketHideClosedInput"),
    ticketRefreshBtn: document.getElementById("ticketRefreshBtn"),
    ticketTitlePatrolBtn: document.getElementById("ticketTitlePatrolBtn"),
    ticketPrioritySelect: document.getElementById("ticketPrioritySelect"),
    ticketPriorityApplyBtn: document.getElementById("ticketPriorityApplyBtn"),
    ticketBatchSelectVisibleBtn: document.getElementById("ticketBatchSelectVisibleBtn"),
    ticketBatchClearSelectionBtn: document.getElementById("ticketBatchClearSelectionBtn"),
    ticketBatchSelectedCountEl: document.getElementById("ticketBatchSelectedCount"),
    ticketAutoPriorityBoostToggle: document.getElementById("ticketAutoPriorityBoostToggle"),
    ticketAutoPriorityBoostBtn: document.getElementById("ticketAutoPriorityBoostBtn"),
    ticketPriorityBatchBtn: document.getElementById("ticketPriorityBatchBtn"),
    ticketPriorityBatchStopBtn: document.getElementById("ticketPriorityBatchStopBtn"),
    ticketTitleNormalizeBtn: document.getElementById("ticketTitleNormalizeBtn"),
    ticketTitleOnNewBtn: document.getElementById("ticketTitleOnNewBtn"),
    pmCsvSelectBtn: document.getElementById("pmCsvSelectBtn"),
    pmPullByRegionBtn: document.getElementById("pmPullByRegionBtn"),
    pmCsvPathLabel: document.getElementById("pmCsvPathLabel"),
    ticketLastUpdatedEl: document.getElementById("ticketLastUpdated"),
    ticketLoadedCountEl: document.getElementById("ticketLoadedCount"),
    ticketListEl: document.getElementById("ticketList"),
    ticketSlaSummaryEl: document.getElementById("ticketSlaSummary"),
    ticketSlaHeaderBadgeEl: document.getElementById("ticketSlaHeaderBadge"),
    ticketSlaReminderToggle: document.getElementById("ticketSlaReminderToggle"),
    ticketSlaNotifyToggle: document.getElementById("ticketSlaNotifyToggle")
  };
})(window.TTDesktop);
